import { existsSync, readFileSync, writeFileSync, copyFileSync } from 'fs';
import { createInterface } from 'readline';
import { randomBytes } from 'crypto';
import path from 'path';
import { green, bold, dim, cyan } from '../utils/colors.js';
import { writeEnvFile } from '../utils/config.js';

function ask(rl: ReturnType<typeof createInterface>, question: string, defaultVal: string): Promise<string> {
  return new Promise((resolve) => {
    rl.question(`  ${question} ${dim(`(${defaultVal})`)}: `, (answer) => {
      resolve(answer.trim() || defaultVal);
    });
  });
}

function kebabCase(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

export async function runInit(): Promise<void> {
  const rl = createInterface({ input: process.stdin, output: process.stdout });

  const policyPath = './vouch.policy.yaml';
  if (existsSync(policyPath)) {
    const overwrite = await ask(rl, 'vouch.policy.yaml exists. Overwrite?', 'n');
    if (overwrite.toLowerCase() !== 'y') {
      process.stdout.write('  Keeping existing policy file.\n');
      rl.close();
      return;
    }
  }

  const dirName = path.basename(process.cwd());
  const projectName = await ask(rl, 'Project name', dirName);
  const projectSlug = await ask(rl, 'Project slug', kebabCase(projectName));
  const apiEndpoint = await ask(rl, 'API endpoint', 'https://vouch.run');

  rl.close();

  // Generate API key
  const apiKey = 'vouch_' + randomBytes(16).toString('hex');

  // Write policy file
  const policyTemplate = `# vouch.policy.yaml
# Generated by vouch init

agent: ${projectSlug}
version: "1.0"

rules:
  - name: confirm_external_calls
    verdict: CONFIRM
    message: "This action calls an external service. Proceed?"
    trigger:
      actionStartsWith: ["http_request", "webhook_call", "api_call"]

  - name: low_confidence_block
    verdict: BLOCK
    blockReason: LOW_CONFIDENCE
    message: "Not confident enough to act. Please clarify your intent."
    trigger:
      contextKey: "confidence"
      contextValueBelow: 0.50
`;
  writeFileSync(policyPath, policyTemplate);

  // Write env file
  writeEnvFile('./.env.vouch', {
    VOUCH_API_ENDPOINT: apiEndpoint,
    VOUCH_API_KEY: apiKey,
    VOUCH_MODE: 'observe',
  });

  // Print summary
  process.stdout.write('\n');
  process.stdout.write(green(bold(`  Vouch initialized for ${projectName}\n`)));
  process.stdout.write('\n');
  process.stdout.write(`  Policy file:  ${cyan('vouch.policy.yaml')}\n`);
  process.stdout.write(`  API key:      ${dim(apiKey.slice(0, 16) + '...')}\n`);
  process.stdout.write(`  Mode:         ${green('observe')} ${dim('(safe - records but never blocks)')}\n`);
  process.stdout.write('\n');
  process.stdout.write(`  ${bold('Next steps:')}\n`);
  process.stdout.write(`    1. Add to .gitignore:  .env.vouch\n`);
  process.stdout.write(`    2. Validate policies:  vouch check\n`);
  process.stdout.write(`    3. Integrate SDK:      npm install vouch-sdk\n`);
  process.stdout.write(`    4. View your page:     ${cyan(`${apiEndpoint}/${projectSlug}`)}\n`);
  process.stdout.write('\n');
  process.stdout.write(`  When ready to enforce policies:\n`);
  process.stdout.write(`    Set VOUCH_MODE=enforce in .env.vouch\n`);
  process.stdout.write('\n');
}
